<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "stagenote"
 *
 * Auto generated by Extension Builder 2018-12-13
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = [
    'title' => 'Stage Note',
    'description' => 'This extension provides a small view which shows the current system (according to URL) and current TYPO3_CONTEXT.',
    'category' => 'plugin',
    'author' => 'Klaus Hörmann-Engl',
    'author_email' => 'kho@world-direct.at',
    'state' => 'alpha',
    'uploadfolder' => 0,
    'createDirs' => '',
    'clearCacheOnLoad' => 0,
    'version' => '1.0.0',
    'constraints' => [
        'depends' => [
            'typo3' => '9.5.0-9.7.99',
        ],
        'conflicts' => [],
        'suggests' => [],
    ],
];
